### ISSUE TITLE
Logo example is content annotation, consider phonetic annotation instead

### ISSUE THREAD

**Issue by duncdrum** [martindholmes/rubyForTEI#7]
see `Images/rbTEI.svg`

this annotates the individual letters of the acronym. This is one way of using ruby, however wouldn't it be more fitting to provide a pronunciation guide using IPA. This would capture the probably more common usage, as well as switch scripts. 

Not strong feelings on this one, just wondering out loud, with an eye to potentially introducing [half-line commentarial insertions](https://github.com/TEIC/TEI/issues/2054#issuecomment-766883318) as a separate entity to TEI at a later point.

**Comment by martindholmes** [comment]
We modelled this on the W3C's own introduction to ruby, section 1.2.1:

https://www.w3.org/TR/2001/WD-ruby-20010216/Overview.html.utf-8#what

**Comment by duncdrum** [comment]
The W3Cs choice is equally unfortunate, imv. The very first example starting of the section, shows the (most common case) [Figure 1.1: Ruby text giving the pronunciation of the base characters.](https://www.w3.org/TR/2001/WD-ruby-20010216/Overview.html.utf-8#fig1.1) , e.g. pronunciation rules for 漢子. I'd say a IPA transcription of `TEI` (pronounced in english) more closely resembles how this works.

**Comment by duncdrum** [comment]
close by ace9c1d1d1a89f1ff3ba6adec1ab0b4509099943 thank you @martindholmes
